# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
- env:
  - GO111MODULE=on
  - CGO_ENABLED=0
  main: ./cmd/n26
  binary: n26
  goos:
   - linux
   - darwin
   - windows
   - freebsd
  goarch:
    - amd64
archives:
  - id: zip
    name_template: "{{ .ProjectName }}-cli-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format: zip
    files:
    - none*
checksum:
  name_template: "checksums.txt"
release:
  github:
    owner: guitmz
    name: n26
  name_template: "{{.Version}}"
changelog:
  sort: asc
  filters:
    exclude:
    - "typo"
    - "^docs:"
    - "^test:"
brews:
  -
   github:
     owner: guitmz
     name: homebrew-tools

   homepage: "https://github.com/guitmz/n26"
   description: "CLI tool for N26 Bank"
   test: |
     system "#{bin}/n26", "--version"

